channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- numpy
- ase =3.23.0
- coverage
- numpy =1.26.3
- scipy =1.14.0
- spglib =2.4.0
- phonopy =2.26.3
- structuretoolkit =0.0.26
- seekpath =2.1.0
- lammps =2023.11.21
- pandas =2.2.2
- pylammpsmpi =0.2.20
- jinja2 =3.1.4
- jupyter-book =1.0.0
