channels:
- conda-forge
dependencies:
- python =3.14
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- ase =3.27.0
- coverage
- numpy =2.3.5
- scipy =1.16.3
- spglib =2.7.0
- phonopy =2.45.1
- structuretoolkit =0.0.38
- seekpath =2.1.0
- lammps =2024.08.29
- pandas =2.3.3
- pylammpsmpi =0.3.7
- jinja2 =3.1.6
- jupyter-book =1.0.0
- pyiron_lammps =0.5.1
- pyiron_vasp =0.2.17
- hatchling =1.27.0
- hatch-vcs =0.5.0
