channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- numpy
- ase =3.22.1
- coverage
- numpy =1.26.3
- scipy =1.12.0
- spglib =2.2.0
- phonopy =2.21.0
- structuretoolkit =0.0.21
- seekpath =2.1.0
- lammps =2023.11.21
- pandas =2.2.0
- pylammpsmpi =0.2.13
- jinja2 =3.1.3
