channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- numpy
- ase =3.23.0
- coverage
- numpy =1.26.3
- scipy =1.14.1
- spglib =2.5.0
- phonopy =2.26.6
- structuretoolkit =0.0.27
- seekpath =2.1.0
- lammps =2024.06.27
- pandas =2.2.2
- pylammpsmpi =0.2.23
- jinja2 =3.1.4
- jupyter-book =1.0.0
