channels:
- conda-forge
dependencies:
- python =3.14
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- ase =3.27.0
- coverage
- numpy =2.4.0
- scipy =1.16.3
- spglib =2.7.0
- phonopy =2.47.1
- structuretoolkit =0.0.39
- seekpath =2.2.1
- lammps =2024.08.29
- pandas =2.3.3
- pylammpsmpi =0.3.9
- jinja2 =3.1.6
- jupyter-book =1.0.0
- lammpsparser =0.0.1
- vaspparser =0.0.1
- hatchling =1.28.0
- hatch-vcs =0.5.0
